# Generated by Django 5.1.1 on 2024-10-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.FileField(upload_to=''),
        ),
    ]
